AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  lambda_funcction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://fellow3/template-out
      Description: ''
      MemorySize: 128
      Timeout: 180
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          lambda_function: lambda_function
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      Layers:
        - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python310:10
        - arn:aws:lambda:us-east-1:580247275435:layer:LambdaInsightsExtension:45
      PackageType: Zip
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:*
                - s3-object-lambda:*
              Resource: '*'
      SnapStart:
        ApplyOn: None
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: cron(0 * * * ? *)
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto